Repository ReactMasters/todolist, pull requests merged in 2022-03, with the labels that each got.

#59 [api] todo -> todoItem, todoGroup -> todoList 로 이름 변경
  packages/api/src/app.module.ts
  packages/api/src/base/base.entity.ts
  packages/api/src/base/output.entity.ts
  packages/api/src/schema.gql
  packages/api/src/tag/dto/create-tag.output.ts
  packages/api/src/tag/dto/list-tags.output.ts
  packages/api/src/tag/entities/tag.entity.ts
  packages/api/src/todo-group/dto/create-todo-group.output.ts
  packages/api/src/todo-group/todo-group.module.ts
  packages/api/src/todo-group/todo-group.resolver.ts
  packages/api/src/todo-group/todo-group.service.ts
  packages/api/src/todo-item/dto/create-todo-item.input.ts
  packages/api/src/todo-item/dto/create-todo-item.output.ts
  packages/api/src/todo-item/dto/todo-status.enum.ts
  packages/api/src/todo-item/entities/todo-item.entity.ts
  packages/api/src/todo-item/todo-item.module.ts
  packages/api/src/todo-item/todo-item.resolver.ts
  packages/api/src/todo-item/todo-item.service.ts
  packages/api/src/todo-list/dto/create-todo-list.input.ts
  packages/api/src/todo-list/dto/create-todo-list.output.ts
  packages/api/src/todo-list/entities/todo-list.entity.ts
  packages/api/src/todo-list/todo-list.module.ts
  packages/api/src/todo-list/todo-list.resolver.ts
  packages/api/src/todo-list/todo-list.service.ts
  packages/api/src/todo/dto/create-todo.output.ts
  packages/api/src/todo/todo.module.ts
  packages/api/src/todo/todo.resolver.ts
  packages/api/src/todo/todo.service.ts
  packages/api/src/user/dto/create-user.output.ts
  packages/api/src/user/entities/user.entity.ts
Labels: 🦾 refactor

#67 [all] 공통 vscode extension을 workspace에 설정하기
  .vscode/extensions.json
Labels: ⚙️ setting

#63 [api] login mutation 생성
  packages/api/package.json
  packages/api/src/constants/index.ts
  packages/api/src/main.ts
  packages/api/src/schema.gql
  packages/api/src/types/index.ts
  packages/api/src/user/dto/login.input.ts
  packages/api/src/user/dto/login.output.ts
  packages/api/src/user/dto/me.output.ts
  packages/api/src/user/user.decorator.ts
  packages/api/src/user/user.guard.ts
  packages/api/src/user/user.resolver.ts
  packages/api/src/user/user.service.ts
  yarn.lock
Labels: ✨ feature

#66 [api] me query 생성
  packages/api/src/main.ts
Labels: ✨ feature

#73 [web] antdesign 설치 및 환경 설정
  packages/web/package.json
  packages/web/pages/index.page.tsx
  yarn.lock
Labels: ⚙️ setting

#68 [web] 기본 컴포넌트를 위한 scss 설정 + Button 컴포넌트 생성
  packages/web/components/AddItem.module.scss.d.ts
  packages/web/components/Item.module.scss.d.ts
  packages/web/lib/apollo/resolvers.ts
  packages/web/lib/apollo/schema.ts
  packages/web/lib/constant.ts
  packages/web/lib/global.scss
  packages/web/lib/graphql.ts
  packages/web/package.json
  packages/web/pages/_app.page.tsx
  packages/web/pages/_document.page.tsx
  packages/web/pages/index.module.scss.d.ts
  packages/web/pages/login/index.module.scss
  packages/web/pages/login/index.page.generated.ts
  packages/web/pages/login/index.page.tsx
  packages/web/styles/_colors.scss
  packages/web/styles/_common.scss
  packages/web/styles/_constants.scss
  packages/web/styles/_fonts.scss
  packages/web/styles/_reset.scss
  packages/web/styles/global.scss
Labels: ✨ feature

#76 [web] SignUp Page 레이아웃 생성
  packages/web/pages/signup/index.module.scss
  packages/web/pages/signup/index.module.scss.d.ts
  packages/web/pages/signup/index.page.tsx
Labels: ✨ feature

#69 [web] Add todo 기능 추가
  packages/web/components/AddTodoHeading/AddTodoHeading.module.scss
  packages/web/components/AddTodoHeading/AddTodoHeading.test.tsx
  packages/web/components/AddTodoHeading/AddTodoHeading.tsx
  packages/web/components/AddTodoItem.module.scss
  packages/web/components/AddTodoItem.tsx
  packages/web/components/TagOption/TagOption.module.scss
  packages/web/components/TagOption/TagOption.test.tsx
  packages/web/components/TagOption/TagOption.tsx
  packages/web/package.json
  packages/web/pages/_app.page.tsx
  packages/web/pages/index.module.scss
  packages/web/pages/index.page.tsx
  packages/web/utils/dateUtil.ts
  packages/web/utils/mockUtil.ts
  yarn.lock
Labels: ✨ feature

#77 [web] 로그인 페이지 & 메인 페이지에서 로그인 유저 정보 확인
  packages/api/src/app.module.ts
  packages/api/src/constants/index.ts
  packages/api/src/main.ts
  packages/web/codegen.yml
  packages/web/components/Button.module.scss
  packages/web/components/Button.tsx
  packages/web/components/Layout.tsx
  packages/web/lib/apollo/client.ts
  packages/web/lib/constant.ts
  packages/web/package.json
  packages/web/pages/index.page.generated.ts
  packages/web/pages/index.page.tsx
  packages/web/pages/login/components/Email.tsx
  packages/web/pages/login/components/LoginForm.generated.ts
  packages/web/pages/login/components/LoginForm.module.scss
  packages/web/pages/login/components/LoginForm.tsx
  packages/web/pages/login/components/LoginHeader.module.scss
  packages/web/pages/login/components/LoginHeader.tsx
  packages/web/pages/login/components/Password.tsx
  packages/web/pages/login/index.page.tsx
  packages/web/pages/login/index.state.ts
  packages/web/pages/ui.page.tsx
  yarn.lock
Labels: ✨ feature
