Repository ReactMasters/todolist, pull requests merged in 2022-04, with the labels that each got.

#88 [web] TodoItem 컴포넌트 추가
  packages/web/__mocks__/matchMedia.mock.js
  packages/web/components/AuthForm/index.module.scss
  packages/web/components/Item.module.scss
  packages/web/components/Item.module.scss.d.ts
  packages/web/components/Item.tsx
  packages/web/components/ItemList.tsx
  packages/web/components/TodoItem/TodoItem.generated.ts
  packages/web/components/TodoItem/TodoItem.module.scss
  packages/web/components/TodoItem/TodoItem.module.scss.d.ts
  packages/web/components/TodoItem/TodoItem.test.tsx
  packages/web/components/TodoItem/TodoItem.tsx
  packages/web/components/TodoList/TodoList.generated.ts
  packages/web/components/TodoList/TodoList.tsx
  packages/web/lib/apollo/localStates.ts
  packages/web/package.json
  packages/web/pages/index.page.tsx
  yarn.lock
Labels: ✨ feature

#91 [web] todoItem 리스트 컴포넌트 생성
  packages/web/components/TodoItem/TodoItem.module.scss
  packages/web/components/TodoList/TodoList.tsx
  packages/web/pages/todolist/todolist.page.tsx
  packages/web/styles/_colors.scss
Labels: ✨ feature

#93 [web] todoList 페이지의 completed 섹션 생성
  packages/web/components/TodoItem/TodoItem.tsx
  packages/web/components/TodoList/TodoList.tsx
Labels: ✨ feature

#101 [web] 파일 저장시 자동 import 정렬
  .vscode/settings.json
  packages/web/.eslintrc.json
  packages/web/components/TodoList/TodoList.tsx
  packages/web/package.json
  yarn.lock
Labels: ⚙️ setting

#102 [web, api] 뮤테이션 쿼리 명 변경
  packages/api/.eslintrc.js
  packages/api/package.json
  packages/api/src/schema.gql
  packages/api/src/tag/dto/add-tag.input.ts
  packages/api/src/tag/dto/add-tag.output.ts
  packages/api/src/tag/tag.resolver.ts
  packages/api/src/tag/tag.service.ts
  packages/api/src/todo-item/dto/add-todo-item.input.ts
  packages/api/src/todo-item/dto/add-todo-item.output.ts
  packages/api/src/todo-item/dto/create-todo-item.output.ts
  packages/api/src/todo-item/todo-item.resolver.ts
  packages/api/src/todo-item/todo-item.service.ts
  packages/api/src/todo-list/dto/add-todo-list.input.ts
  packages/api/src/todo-list/dto/add-todo-list.output.ts
  packages/api/src/todo-list/todo-list.resolver.ts
  packages/api/src/todo-list/todo-list.service.ts
  packages/api/src/user/dto/login.output.ts
  packages/api/src/user/dto/signin.input.ts
  packages/api/src/user/dto/signin.output.ts
  packages/api/src/user/dto/signup.input.ts
  packages/api/src/user/dto/signup.output.ts
  packages/api/src/user/dto/update-user.input.ts
  packages/api/src/user/user.resolver.ts
  packages/api/src/user/user.service.ts
  packages/web/codegen.yml
  packages/web/components/AuthForm/index.generated.ts
  packages/web/components/AuthForm/index.tsx
  packages/web/components/TodoItem/TodoItem.generated.ts
  packages/web/components/TodoList/TodoList.generated.ts
  packages/web/lib/graphql/query.generated.ts
  packages/web/lib/graphql/types.ts
  packages/web/pages/index.page.generated.ts
Labels: 🦾 refactor

#104 [web, api] 파일 저장시 unused import 자동 삭제
  packages/api/.eslintrc.js
  packages/api/package.json
  packages/web/.eslintrc.json
  packages/web/package.json
  yarn.lock
Labels: ⚙️ setting
